### PR TITLE
Systemd services restart policy change to always

### LINKED ISSUE #1208: Kubelet and etcd fail to restart on signal=PIPE
**This is a BUG REPORT and FEATURE REQUEST**:

**What happened**: Reconfigured /etc/systemd/journald.conf on our k8s cluster as we noticed that systemd-journald wasn't keeping persistent logs (Storage=auto is the default, which doesn't store previous boot logs... pretty useless when a server crashes).  After updating the file, restarted systemd-journalctld (systemctl restart systemd-journald).  Kubelets all crashed with signal=PIPE.  Kubelet services did not restart.

**What you expected to happen**: Kubelet services would restart since they weren't explicitly asked to stop via systemd.

**How to reproduce it (as minimally and precisely as possible)**: systemctl restart systemd-journald; systemctl status kubelet (it will be dead)

**Anything else we need to know?**: First of all, the service behaved exactly as configured, but this should not be the default. The service is setup with a Restart=on-failure.  This is not sufficient to cover crashes or restarts of systemd-journald.  A value of Restart=always is the only better option, and will still allow it to stop via systemctl commands as expected.

**Environment**:
- Kismatic version (use `kismatic version`):   Version: 1.9.0 Built: Wed Feb 28 15:18:53 UTC 2018  Go Version: go1.9.3
- Plan file Gist (remove sensitive information if any): n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): Linux xxx.yyyy.com 4.15.4-1.el7.elrepo.x86_64 #1 SMP Sat Feb 17 13:35:20 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by jlmeeker**
Changed systemd services so they restart "always" instead of "on-failure"
Fixes #1208

### CODE REVIEW

**Comment by dkoshkin** [comment]
I tested this locally changing to `always` and the kubelet did not come up, in your testing were you able to get the kubelet working again?
```
[root@ip-10-0-0-127 centos]# systemctl restart systemd-journald.service
[root@ip-10-0-0-127 centos]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-04-26 14:33:25 UTC; 13min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 17313 (kubelet)
   Memory: 36.5M
   CGroup: /system.slice/kubelet.service
           └─17313 /usr/bin/kubelet --allow-privileged=true --authorization-mode=Webhook --cadvisor-port=0 --client-ca-file=/etc/kubernetes/pki/ca.pem --cluster-dns=172.20.0.2 --cluster-domain=cluster....

...

[root@ip-10-0-0-127 centos]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2018-04-26 14:47:18 UTC; 445ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 17313 ExecStart=/usr/bin/kubelet --allow-privileged=true --authorization-mode=Webhook --cadvisor-port=0 --client-ca-file=/etc/kubernetes/pki/ca.pem --cluster-dns=172.20.0.2 --cluster-domain=cluster.local --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --container-runtime=docker --docker=unix:///var/run/docker.sock --event-qps=0 --hostname-override=ip-10-0-0-127.ec2.internal --kubeconfig=/etc/kubernetes/kubelet.conf --make-iptables-util-chains=true --network-plugin=cni --node-ip=10.0.0.127 --node-labels=,node-role.kubernetes.io/master= --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=false --serialize-image-pulls=false --streaming-connection-idle-timeout=0 --tls-cert-file=/etc/kubernetes/pki/kubelet.pem --tls-private-key-file=/etc/kubernetes/pki/kubelet-key.pem --v=2 Restart=always (code=killed, signal=PIPE)
 Main PID: 17313 (code=killed, signal=PIPE)

...

[root@ip-10-0-0-127 centos]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2018-04-26 14:47:18 UTC; 55s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 17313 ExecStart=/usr/bin/kubelet --allow-privileged=true --authorization-mode=Webhook --cadvisor-port=0 --client-ca-file=/etc/kubernetes/pki/ca.pem --cluster-dns=172.20.0.2 --cluster-domain=cluster.local --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --container-runtime=docker --docker=unix:///var/run/docker.sock --event-qps=0 --hostname-override=ip-10-0-0-127.ec2.internal --kubeconfig=/etc/kubernetes/kubelet.conf --make-iptables-util-chains=true --network-plugin=cni --node-ip=10.0.0.127 --node-labels=,node-role.kubernetes.io/master= --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=false --serialize-image-pulls=false --streaming-connection-idle-timeout=0 --tls-cert-file=/etc/kubernetes/pki/kubelet.pem --tls-private-key-file=/etc/kubernetes/pki/kubelet-key.pem --v=2 Restart=always (code=killed, signal=PIPE)
 Main PID: 17313 (code=killed, signal=PIPE)
...
```

**Comment by jlmeeker** [comment]
Sure enough it does not work.  Hmmm.... I expected systemd to behave as their docs say... so no more assumptions.  In theory this PR should work as restart=always works for clean and unclean exit codes as per:  https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

A list of exit codes is included on the same page.  This may have to be handled upstream in the kubelet so it can retry connecting to journald.

OS: CentOS Linux release 7.4.1708 (Core) 
Kernel: 4.15.10-1.el7.elrepo.x86_64
Kubelet ver: kubelet-1.9.2-0.x86_64
SystemD ver: systemd-219-42.el7_4.4.x86_64

**Comment by TimWoolford** [comment]
Wouldn't it be safer to change the kubelet.service to include
```
RestartForceExitStatus=SIGPIPE
```
??

**Comment by jlmeeker** [comment]
@TimWoolford Thanks for the suggestion! That option did the trick.  After bouncing systemd-journald the kubelet restarted as desired.

**Pull request closed without merging**
