### PR TITLE
Stop kismatic-inspector even on failure

### PR DESCRIPTION
**Pull request by dkoshkin**

### CODE REVIEW

**Comment by alexbrand** [comment]
Does the ansible version that we use run the "rescue" block in case of failure? The ansible team mentioned that they had a bug that was fixed in 2.2.0

**Comment by dkoshkin** [comment]
I tested with the version we have and it worked

**Comment by alexbrand** [comment]
Cool. Sounds like we can merge this, and close #142 and #105.

**Comment by dkoshkin** [comment]
Fixes #142 and Fixes #105

**Pull request merged**
