### PR TITLE
Make host file modification more efficient

### PR DESCRIPTION
**Pull request by alexbrand**
With this change, modifying hosts files scales linearly. 

Added coverage in the integration suite for the hosts file modification feature.

### CODE REVIEW

**Comment by dkoshkin** [comment]
What happens if you rerun this with different data, does the data between the markers gets replaced? 

Tying to think what would happen when adding a worker.

**Comment by alexbrand** [comment]
Excellent observation. Thanks @dkoshkin 

I'll investigate and add a test as well.

**Comment by alexbrand** [comment]
I added a test where we go through the add-worker workflow. I also verified that the hosts files get updated when adding a worker.

**Comment by dkoshkin** [comment]
Did you do a manual sanity check to verify that the hosts file was updated or just relying on the successful install?

**Comment by alexbrand** [comment]
Logged into the machine to verify.

**Comment by dkoshkin** [comment]
That works, LGTM

**Pull request merged**
