### PR TITLE
Added proxy config under environment for Helm

### LINKED ISSUE #735: Initialize Helm fails when using a proxy
When a proxy is being used, `run helm init` can fail during the install because the proxy variables may not be configured on the node. 

The following Error snippet from a `kismatic install apply` run shows this:
```
Initialize Helm and Start Tiller                                                [ERROR]
- Task: run helm init
  hostname:                                                                            [ERROR]
---- STDOUT ----
Creating /home/kismaticuser/.helm/repository/repositories.yaml 
---- STDERR ----
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.10.240:443: i/o timeout
---------------
error installing: error running playbook: error running ansible: exit status 2
```

### PR DESCRIPTION
**Pull request by jaycoon**
Fixes #735 "Initialize Helm fails when using a proxy"

### CODE REVIEW

**Comment by dkoshkin** [comment]
Did you not need to add the same proxy settings in the next command?
```
      - name: "add kismatic helm repo"
        local_action: command ../../helm repo add kismatic https://apprenda.github.io/kismatic-charts/
        become: no
        environment:
          KUBECONFIG: "{{ local_kubeconfig_directory }}"
        when: disconnected_installation|bool != true
```

**Comment by dkoshkin** [comment]
@jaycoon please see comment above ^

**Comment by jaycoon** [comment]
I didn't add the proxy settings to `helm repo add`

**Comment by dkoshkin** [comment]
LGTM! Thanks @jaycoon

**Pull request merged**
