### PR TITLE
Use the --skip-refresh helm flag when doing a disconnected install

### LINKED ISSUE #763: Helm init may fail during disconnected installs
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
Task `helm init` fails when trying to add the default repo `https://kubernetes-charts.storage.googleapis.com/index.yaml`

**What you expected to happen**:
On disconnected installs `helm init` should use the `--skip-refresh` flag

**How to reproduce it (as minimally and precisely as possible)**:
Run a disconnected install with a bastion node that is also disconnected and does not have the `helm` cache locally.

### PR DESCRIPTION
**Pull request by dkoshkin**
Fixes #763

### CODE REVIEW

**Comment by alexbrand** [comment]
Does this mean the repository won't be set up locally if you are doing a disconnected install? Makes sense to me, but want to understand. I tried looking at the helm docs but it's not entirely clear to me.

```
      --skip-refresh             do not refresh (download) the local repository cache
```

**Comment by dkoshkin** [comment]
Just looked into this, it sets it up as a repo, so `help repo list` will still show it, but it doesn't try to fetch the `~/helm/repository/cache/stable-index.yaml` file that contains the list of all charts in the repo.

**Comment by alexbrand** [comment]
This LGTM. If there's no internet access, there is no way for us to fetch the repo information. 

I think @mssch had some thoughts on this though.

**Comment by mssch** [comment]
No specific thoughts, just can confirm #763 since I ran into it during a disconnected install, this should fix it indeed.
LGTM

**Pull request merged**
