### PR TITLE
Update calico/kube-controllers to v1.0.4

### PR DESCRIPTION
**Pull request by jhutchins**

### CODE REVIEW

**Comment by dkoshkin** [comment]
Please modify the rest of the components with the latest `v2.6.9` versions. Also modify the version in the [README](https://github.com/apprenda/kismatic/blob/master/README.md)

**Comment by jhutchins** [comment]
@dkoshkin done

**Comment by dkoshkin** [comment]
A couple more images [calico/ctl](https://github.com/jhutchins/kismatic/blob/a451e99b21356ec8b9b9de1dc7212ba7139ced0f/ansible/group_vars/container_images.yaml#L21) and [calico/cni](https://github.com/jhutchins/kismatic/blob/a451e99b21356ec8b9b9de1dc7212ba7139ced0f/ansible/group_vars/container_images.yaml#L24) from https://docs.projectcalico.org/v2.6/releases/

**Comment by jhutchins** [comment]
Sorry I missed those, that was sloppy.

**Comment by dkoshkin** [comment]
LGTM! Thanks

**Pull request merged**
