### PR TITLE
Add upgrade test from 1.3.1

### PR DESCRIPTION
**Pull request by alexbrand**
Adding a new test to cover upgrades from v1.3.1

### CODE REVIEW

**Comment by dkoshkin** [comment]
LGTM

**Comment by dkoshkin** [comment]
Can you take a look at https://github.com/apprenda/kismatic/blob/master/integration/upgrade_test.go#L33, this should be CentOS, we are using Ubuntu for the large test already.

**Comment by alexbrand** [comment]
Good catch. Done.

**Comment by dkoshkin** [comment]
Looks good.

**Pull request merged**
