### PR TITLE
Expose calico log_level in the plan file

### LINKED ISSUE #779: Make calico log level parameterized
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:
Calico info logs spam a lot of 'iptables' info filling up the disk. We would like to keep the log level to WARNING. [Currently, it is hardcoded to INFO in ansible roles](https://github.com/apprenda/kismatic/blob/18987af8e3c6844b3b3ed2fe38bc3532f6e6eb37/ansible/roles/calico/templates/calico.yaml#L22). Solution would be to make it parameterized and pick up from config yaml (if not provided, only then keep it as INFO)

**What you expected to happen**:
Parameterized way to provided calico log level

**How to reproduce it (as minimally and precisely as possible)**:
Grep the calico logs. They all should say INFO.

### PR DESCRIPTION
**Pull request by dkoshkin**
Fixes #779 

Calico [doc](https://docs.projectcalico.org/v2.5/reference/cni-plugin/configuration)

### CODE REVIEW

**Comment by alexbrand** [comment]
LGTM!

**Comment by alexbrand** [comment]
Now that I think about it more... What happens during an upgrade?

**Comment by dkoshkin** [comment]
It defaults to `info` even if the field is missing in the plan file. If the user changes during upgrade, it would be set and restarted.

**Comment by alexbrand** [comment]
Sweet!

**Comment by prat0318** [comment]
Awesome.

**Pull request merged**
