### PR TITLE
Add make target for focused integration test

### PR DESCRIPTION
**Pull request by alexbrand**
Makes it easier to run a specific test using an env var.

### CODE REVIEW

**Comment by dkoshkin** [comment]
Yes!! Do you think it would be beneficial to also add some sort of an ID to each test to make it easier "focusing" on a single test?

**Comment by alexbrand** [comment]
Our spec names should be all we need for this. If not, this means the names we have are not specific/descriptive enough.

**Comment by dkoshkin** [comment]
They do, I meant having shorted names `INSTALL_1`, its just a small inconvenience copy/paste multiple lines :)

**Comment by alexbrand** [comment]
We could, but I think it'll get messy over time and hard to maintain. I have found using regexp in the focus argument to be powerful enough in all cases I've run into.

**Comment by dkoshkin** [comment]
LGTM

**Pull request merged**
