### PR TITLE
Adding a releases template

### PR DESCRIPTION
**Pull request by swade1987**
My plan here is for each release to have a dedicated file underneath `releases`.

Each release will have a filename of `v1.7.0-release.md`

Then in the releases tab on GitHub, we can simply link to the necessary set of release notes.

### CODE REVIEW

**Comment by alexbrand** [comment]
I like it!

**Comment by swade1987** [comment]
Thanks @alexbrand

**Comment by emmetthitz** [comment]
LGTM!

**Comment by swade1987** [comment]
Happy for me to merge?

**Pull request merged**
