### PR TITLE
Helm upgrade from v2.6.1 to v.2.7.0

### LINKED ISSUE #891: Upgrade Helm
Helm currently has a newer patch release (2.6.2) than what we are using (2.6.1), which includes bug fixes. 

They've also released 2.7.0 version that is compiled against Kubernetes 1.8. It might be worthwhile to make the jump?

At a minimum we should upgrade to 2.6.2.

### PR DESCRIPTION
**Pull request by swade1987**
The main reason for this is it contains Kubernetes 1.8 support.

Closes #891

### CODE REVIEW

**Comment by alexbrand** [comment]
This LGTM, but it seems like Calico changes sneaked into the PR.

**Comment by swade1987** [comment]
I will revert the commits and we can squash.

**Comment by swade1987** [comment]
@alexbrand please squash the commits when you merge :)

**Comment by dkoshkin** [comment]
LGTM

**Comment by swade1987** [comment]
@dkoshkin I think we have an issue whereby this commit has removed the calico metrics from master [see here](https://github.com/apprenda/kismatic/commit/9082d7f10cbc3ce60844271ebebf9740d459d76d).

Therefore calico metrics aren't exposed in KET 1.6.1 or newer as listed on the release notes.

**Comment by dkoshkin** [comment]
Thanks @swade1987 looks like some strange git merging.

**Comment by swade1987** [comment]
No problem @dkoshkin any ETA to put the changes back?

**Pull request merged**
