### PR TITLE
Fix typo in the end construct

### PR DESCRIPTION
**Pull request by prat0318**
`end` should be replaced by `endif`.

### CODE REVIEW

**Comment by dkoshkin** [comment]
Thanks @prat0318 , did you notice a failure with this? Strange that Ansible doesn't throw a templating error here.

**Comment by prat0318** [comment]
Yeah, saw a parse error during `upgrade`, which got fixed when i changed to `endif`.

**Comment by dkoshkin** [comment]
@alexbrand do you see a problem merging this?

**Comment by alexbrand** [comment]
LGTM! Although it would be nice to have a post-mortem on why this passed tests.

**Comment by dkoshkin** [comment]
We have an integration test that only does this upgrade on Ubuntu and not on CentOS where this would impact it.

**Pull request merged**
