### PR TITLE
Support a signed docker registry

### PR DESCRIPTION
**Pull request by dkoshkin**

### CODE REVIEW

**Comment by alexbrand** [comment]
How does this fail if the provided registry has a self-signed cert, or a signing cert that is not trusted by the machine?

**Comment by alexbrand** [comment]
I am wondering if there's a preflight check we add for this

**Comment by dkoshkin** [comment]
I was trying to think of one too but docker wont be installed at that point.

**Comment by alexbrand** [comment]
Might be overkill, but maybe we can hit the registry over HTTPS at `/v2/`. I am not sure if the `v1` API is still in use though. In any case, if we get a 200 or 401 it should be OK.

**Comment by alexbrand** [comment]
Decided to punt on the preflight check. We will add one if users run into issues.

**Pull request merged**
