### PR TITLE
Add json support to info cmd

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #365

### CODE REVIEW

**Comment by dkoshkin** [comment]
What does this look like with `--json`?

**Comment by alexbrand** [comment]
Yeah. I thought about but decided to keep it consistent with `apply`. I am torn between them, so I'll let you choose.

**Comment by alexbrand** [comment]
Sample output:
```
# ./kismatic info -o json
{
  "EarliestVersion": "1.3.0-alpha.0-dirty",
  "LatestVersion": "1.3.0-alpha.0-dirty",
  "IsTransitioning": false,
  "Nodes": [
    {
      "Node": {
        "Host": "node001",
        "IP": "192.168.42.2",
        "InternalIP": ""
      },
      "Roles": [
        "master",
        "etcd",
        "worker",
        "ingress"
      ],
      "Version": "1.3.0-alpha.0-dirty"
    }
  ]
}

# bin/darwin/kismatic version -o json
{
    "Version": "1.3.0-alpha.0-1-g065c691-dirty",
    "BuildDate": "Thu Mar  2 22:13:03 UTC 2017",
    "GoVersion": "go1.8"
}

**Comment by dkoshkin** [comment]
LGTM

**Comment by alexbrand** [comment]
Tested manually

**Pull request merged**
