### PR TITLE
Update kube-dns rc to deployment

### LINKED ISSUE #351: HA deployment for cluster DNS
Currently, we deploy kube-dns as a replication controller with a single replica. In order to support an online upgrade, DNS must have more than one replica running on the cluster.

- [x] Investigate community recommendations when it comes to multiple kube-dns pods running
- [x] Move kube-dns to a Kubernetes deployment if it makes sense
- [x] Increase replica count of kube-dns deployment

### PR DESCRIPTION
**Pull request by dkoshkin**
Fixes #351 

Update kube-dns yaml file to a k8s deployment similar to https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/addons/dns/skydns-rc.yaml.base

There is no image version changes.

### CODE REVIEW

**Comment by dkoshkin** [comment]
Running DNS with multiple replicas is supported in the community, in fact there is a DNS [autoscaler](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler) that is just a k8s deployment, I dont think KET should install this as this will be better left to the operator. 

It is also safe for the operator to manually scale replicas up and down based on the load.

**Comment by alexbrand** [comment]
Would having 100 DNS pods on a cluster with 100 worker nodes be detrimental to performance?

**Comment by alexbrand** [comment]
I misread the change. LGTM!

**Comment by alexbrand** [comment]
Although it would be good to know why the healthz endpoint changed.

**Comment by dkoshkin** [comment]
Found the [issue](https://github.com/kubernetes/kubernetes/issues/30633) related to the health endpoint.

Looks like the way we had it was a bug and it should have been this way all along since it was merged in back in August of last year.

**Pull request merged**
