### PR TITLE
SSH and info usability changes

### LINKED ISSUE #472: `kismatic info` returns IP addresses, but that information can't be used to run `kismatic ssh` on ip.
This is more of a usability bug, but see below: 

```
[root@hqs-kuber08 kismatic-1.3.0]# kismatic info
Cluster: v1.3.0

Nodes:
  - 10.5.6.231: v1.3.0 [etcd]
  - 10.5.6.232: v1.3.0 [etcd]
  - 10.5.6.233: v1.3.0 [etcd]
  - 10.5.6.230: v1.3.0 [master][root@hqs-kuber08 kismatic-1.3.0]# kismatic info
Cluster: v1.3.0

Nodes:
  - 10.5.6.231: v1.3.0 [etcd]
  - 10.5.6.232: v1.3.0 [etcd]
  - 10.5.6.233: v1.3.0 [etcd]
  - 10.5.6.230: v1.3.0 [master]
  - 10.5.6.234: v1.3.0 [worker ingress storage]
  - 10.5.6.235: v1.3.0 [worker ingress storage]
  - 10.5.6.236: v1.3.0 [worker storage]

[root@hqs-kuber08 kismatic-1.3.0]# kismatic ssh 10.5.6.230
SSH error "10.5.6.230": node "10.5.6.230" not found in the plan
```

My proposal here would be to add an improvement to search for both the hostname and/or ip, or add the host information here under `kismatic info` to direct a consumer to use the hostname for `kismatic ssh`

### PR DESCRIPTION
**Pull request by dkoshkin**
Fixes #472 

The `info` command should print the `hostnames` instead of IPs as the IPs are not really used anywhere. The `hostnames` are used for k8s node names.

Support public IPs in `ssh` command, sometimes the user may know the public IP instead of the hostname.

### CODE REVIEW

**Comment by alexbrand** [comment]
Given that we are already in this code, I am thinking we should make this more `kubectl`-like. Something similar to:
```
# ./kismatic info
Kismatic Verison: v1.3.1

Nodes:
Name            IP           Roles           Kismatic Version
etcd01     192.168.1.1       etcd            v1.3.1
master01   192.168.1.2       master          v1.3.1
worker01   192.168.1.2       worker,ingress  v1.3.1
```

@dkoshkin wdyt?

**Comment by dkoshkin** [comment]
```
➜  out git:(ssh-and-info) ✗ ./kismatic info -o json
{
  "EarliestVersion": "1.3.1-beta.1",
  "LatestVersion": "1.3.1-beta.1",
  "IsTransitioning": false,
  "Nodes": [
    {
      "Node": {
        "Host": "etcd001",
        "IP": "192.168.42.2",
        "InternalIP": ""
      },
      "Roles": [
        "etcd"
      ],
      "Version": "1.3.1-beta.1"
    },
    {
      "Node": {
        "Host": "master001",
        "IP": "192.168.42.3",
        "InternalIP": ""
      },
      "Roles": [
        "master"
      ],
      "Version": "1.3.1-beta.1"
    },
    {
      "Node": {
        "Host": "worker001",
        "IP": "192.168.42.4",
        "InternalIP": ""
      },
      "Roles": [
        "worker",
        "ingress"
      ],
      "Version": "1.3.1-beta.1"
    }
  ]
}
➜  out git:(ssh-and-info) ✗ ./kismatic info
Kismatic Version: v1.3.1-beta.1

Nodes:
Name        IP             Roles            Kismatic Version
etcd001     192.168.42.2   etcd             1.3.1-beta.1
master001   192.168.42.3   master           1.3.1-beta.1
worker001   192.168.42.4   worker,ingress   1.3.1-beta.1
```

**Comment by alexbrand** [comment]
Awesome @dkoshkin 

Does it look fine when a single node has all roles? Also what happens with really long FQDNs?

**Comment by dkoshkin** [comment]
```
➜  out git:(ssh-and-info) ✗ ./kismatic info
Kismatic Version: v1.3.1-beta.1

Nodes:
Name                                                IP             Roles                                Kismatic Version
etcd001.etcd001.etcd001.etcd001                     192.168.42.2   master,etcd,worker,ingress,storage   1.3.1-beta.1
master001.master001.master001.master001.master001   192.168.42.3   master                               1.3.1-beta.1
worker001                                           192.168.42.4   worker,ingress                       1.3.1-beta.1
```

**Comment by alexbrand** [comment]
LGTM

**Pull request merged**
