### PR TITLE
Cluster components version labels

### PR DESCRIPTION
**Pull request by willvrny**
This adds version labels to cluster components as requested in issue #629.

I've added these labels to pods as this seemed like a better resource to label. Also if using a log forwarder for getting metadata it will fetch the labels from the pod.

I've added labels for all containers to cover when a resource has multiple containers with different versions.

The only component missing this label in Tiller as it is installed via `helm init`. To add this we'd need to install Tiller via normal Kubernetes resource files.

I also set explicit selectors on components that were missing them as they would default to using all labels on a pod which includes the version label. This version is likely to change between upgrades. In Kubernetes deployment `apps/v1beta2` selectors will become mandatory:

>In API version apps/v1beta2, .spec.selector and .metadata.labels no longer default to .spec.template.metadata.labels if not set. So they must be set explicitly. Also note that .spec.selector is immutable after creation of the Deployment in apps/v1beta2 - [Kubernetes Docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector)

### CODE REVIEW

**Comment by alexbrand** [comment]
Interesting - so even when the component has a single container, we will still use `blah_component_version`?

**Comment by willvrny** [comment]
@alexbrand Yes for consistency. At some point it might be good to review all the templates to ensure consistency.

**Comment by jaycoon** [comment]
I don't like adding all these labels to the spec templates, we need a better solution. The metrics are exposed if using kube-state-metrics, though there are other options to surface these for Prometheus. It definitely shouldn't be a default label though.

**Comment by willvrny** [comment]
@jaycoon @alexbrand There's also the scenario of getting this metadata into the logs. It might be useful to see component version if you start seeing errors in the logs. You could track it down to when the version changed.

We should ideally be enforcing a consistent set of metrics across all our components.

**Comment by swade1987** [comment]
@jaycoon it's about having all necessary information when performing root-cause analysis and log reviewal.

Note: Kube-state-metrics is only useful when monitoring and alerting, when you need to start looking at the logs this information isn't available out the box.

**Comment by willvrny** [comment]
@alexbrand Is this okay to merge?

**Comment by alexbrand** [comment]
I think it looks good to me, but it seems like there was some disagreement on it? 

cc @jaycoon @dkoshkin

**Comment by dkoshkin** [comment]
LGTM!

**Comment by jaycoon** [comment]
Sorry guys, I still do not like putting image component versions in a label... this kind of data should be in an annotation. e.g.

```
kubedns/dnsmasq/version: "1.14.5"
kubedns/sidercar/version: "1.14.5"
```

Annotations are used for debugging, labels are for selectors and making decisions... it doesn't make sense to put component versions in a label (unless you need it to make a scheduling decision, which is not the use case being described here).

**Comment by alexbrand** [comment]
I actually agree with @jaycoon and brought that point up when the issue was originally filed.

**Comment by dkoshkin** [comment]
+1 with @jaycoon however as I understand this, prometheus uses labels and not annotations.

**Comment by swade1987** [comment]
Labels are useful for logging, you can't easily obtain the annotations from tools like fluentbit.

**Comment by swade1987** [comment]
What is the agreement on how to take this forward?

**Comment by emmetthitz** [comment]
This should also be moved to a branch and run against CI. I don't think this nor #903 will have any issues, but just to be safe.

**Comment by swade1987** [comment]
What is the status on this one?

**Pull request closed without merging**
