### PR TITLE
[WIP] Add support for cluster monitoring, prometheus and grafana

### LINKED ISSUE #551: Cluster Monitoring
Add monitoring to the cluster.  
Using prometheus and grafana Helm charts.

Plan file changes:
```
cluster:
...
features:
  package_manager:
    enabled: true
    provider: helm
  heapster:
    enabled: true
    storage:
      persistent_volume_claim: ""
  monitoring:
    enabled: true
    prometheus:
      values: "" # path to the file to override any helm variable
      storage:
        alertmanager_persistent_volume_claim: ""
        server_persistent_volume_claim: ""
    grafana:
      values: ""
      storage:
        server_persistent_volume_claim: ""
```

Inspector changes:
**node exporter port**: 9100

Package Changes:
```
    Image: appropriate/curl:latest
    Image: quay.io/coreos/grafana-watcher:v0.0.4
    Image: grafana/grafana:latest
    Image: prom/alertmanager:v0.5.1
    Image: jimmidyson/configmap-reload:v0.1
    Image: prom/node-exporter:v0.13.0
    Image: gcr.io/google_containers/kube-state-metrics:v0.4.1
    Image: prom/prometheus:v1.5.2
```

Things to consider
- should `values:` be a `map[string]string` or the path to a file, both?
  - this will impact the ability to add/modify graphs to deploy:
  - leaning towards to both, helm already [handles all the merging](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md)
- ~if a user wants to upgrade a chart how do they get the variables we used to set it up~ - there is a flag on `helm upgrade --reuse-values` that will preserve the previous release values, they will be joined with any new values passed in
- how to monitor etcd?

### PR DESCRIPTION
**Pull request by dkoshkin**
Fixes #551 

This PR installs Prometheus and Grafana monitoring stack using Helm charts.  
It also moves `package_manager` to `addons:` section outside of `features:`

Two new questions are also introduced when running `kismatic install plan`:
```
➜  out git:(monitoring) ✗ ./kismatic install plan
Plan your Kubernetes cluster:
=> Number of etcd nodes [3]:
=> Number of master nodes [2]:
=> Number of worker nodes [3]:
=> Number of ingress nodes (optional, set to 0 if not required) [2]:
=> Number of storage nodes (optional, set to 0 if not required) [0]:
=> Number of existing NFS volumes to be attached [0]:
Cluster Add-Ons:
=> Enable package manager (set to 'none' if not required) [helm none]:
Cluster Features:
=> Enable cluster monitoring (set to 'none' if not required) [prometheus none]:

Generating installation plan file template with:
- 3 etcd nodes
- 2 master nodes
- 3 worker nodes
- 2 ingress nodes
- 0 storage nodes
- 0 nfs volumes
- enabled cluster package manager: helm
- enabled cluster monitoring: prometheus

Wrote plan file template to "kismatic-cluster.yaml"
Edit the plan file to further describe your cluster. Once ready, execute the "install validate" command to proceed.
```
Plan file changes:
```
addons:
  package_manager:
    enabled: true
    provider: helm
features:
  monitoring:
  - provider: prometheus
    name: cluster-monitoring
    namespace: monitoring
    options:
      alertmanager_pvc_name: ""
      grafana_config_file: ""
      grafana_pvc_name: ""
      prometheus_config_file: ""
      prometheus_pvc_name: ""
```

**TODO**
- [ ] Add images to `offline` package
- [ ] Move charts to a different GH repo from `dkoshkin/charts`
- [ ] Figure out service type and integration, if any with ingress
- [x] Figure out an automated way to include the chart `tar` files
- [x] Integration tests!

### CODE REVIEW

**Comment by alexbrand** [comment]
Is the dashboards.yaml file autogenerated somehow? 3.5k lines!

**Comment by dkoshkin** [comment]
It is heavily based on the [prometheus operator ones](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml).

**Comment by alexbrand** [comment]
Some things that come to mind:
* Can we have a directory listing of the exploded tarball?
* How does grafana talk to prometheus? Are there any security considerations that need to be made?
* Have you had a chance to think more about how we'll build the helm charts? We certainly don't want the tarballs in source control
* Are we including the helm "values" config file in the package? Or do I have to go get it from somewhere?

**Comment by dkoshkin** [comment]
Closing as we will not have a `features` value in the plan file.

**Pull request closed without merging**
