### PR TITLE
adding logo folder and files to the project

### PR DESCRIPTION
**Pull request by jessicamaslyn**
changing the README.md to source the new logo location

### CODE REVIEW

**Comment by alexbrand** [comment]
Thanks @jessicamaslyn! I'd rather not have another top-level folder. What do you think about putting the logos inside the `docs` dir, or maybe `docs/logo`?

**Comment by jessicamaslyn** [comment]
Hey Alex, I was following the same format as https://github.com/kubernetes/kubernetes but moving it to docs/logo is no problem.

**Comment by jaycoon** [comment]
@alexbrand - should we create a docs/images or docs/img? We will likely have other diagrams to add later

**Comment by alexbrand** [comment]
@jessicamaslyn gotcha! I think having it inside docs makes more sense. What do you think?

@jaycoon That sounds like a great idea. Feel free to move existing images into that dir if it makes sense.

I know some of this will have an effect on our docs site when we build one. CC'ing @dkoshkin for his thoughts on this.

**Comment by jessicamaslyn** [comment]
how about 2 separate folders within docs, one for logos and one for diagram images? Or would this be too many different folders?

**Comment by alexbrand** [comment]
@jessicamaslyn I have no problem with that. It's the root dir that I'd like to declutter 😄

**Comment by jessicamaslyn** [comment]
all set

**Comment by alexbrand** [comment]
LGTM! We can rework this if necessary for docs site.

**Pull request merged**
