### PR TITLE
Make port preflight checks idempotent

### LINKED ISSUE #928: Improve preflight checks so that they can be run after the cluster is up
Currently, if an installation fails midway, the user is forced to skip preflight checks because some of the checks fail after specific installation steps have completed. For example, the API server port checks fail once the API server is running.

Ideally, the inspector should be able to run against a running cluster so that a) the user doesn't have to add an extra flag when retrying a failed installation, b) we get closer to an idempotent `apply` command.

This will also play an important role in our cluster controller.

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #928

### CODE REVIEW

**Comment by dkoshkin** [comment]
Awesome LGTM!

**Comment by alexbrand** [comment]
When working on this I was using Ubuntu. Before merging, I wanted to make sure that `lsof` is installed by default in RHEL / CentOS. Unfortunately, it isn't. So I'll have to rework this.

**Comment by dkoshkin** [comment]
Even more LGTM! This is some cool stuff.

**Comment by emmetthitz** [comment]
Right? No more need to --skip-preflight hype

**Comment by dkoshkin** [comment]
We are doing an upgrade and it made me think that we should add port preflights to it. What do you guys think?

**Comment by emmetthitz** [comment]
@dkoshkin elaborate?

**Comment by swade1987** [comment]
@alexbrand @dkoshkin @emmetthitz is this going to be available in the 1.7.0 release?

**Pull request merged**
