### PR TITLE
Add prometheus scrape annotation

### LINKED ISSUE #1002: Add prometheus scrape annotations to calico and kube-proxy daemonset
Right now we don't have the annotations to scrape the calico and kube-proxy daemonsets.

### PR DESCRIPTION
**Pull request by swade1987**
closes #1002

### CODE REVIEW

**Comment by dkoshkin** [comment]
Are there any pods that need to be scraped, weave, kube-proxy anything else?

**Comment by swade1987** [comment]
@dkoshkin kube-proxy does as well.

**Comment by dkoshkin** [comment]
Can you make this PR more generic and add the annotation to all the pods that need it.

**Comment by swade1987** [comment]
@dkoshkin added to include kube-proxy

**Comment by swade1987** [comment]
please squash this when merging.

**Comment by dkoshkin** [comment]
LGTM!

**Pull request merged**
